# Look for available options and their descriptions in: https://github.com/thedodd/trunk/blob/master/Trunk.toml

[build]
target = "dist_templates/web/index.html"
release = true
dist = "dist/itch_io"
filehash = true
# By default, `trunk` generates absolute path links to resources.
#   Sadly, they do not work on itch.io, because the game is served
#   from the subdirectory there. Therefore, we need to replace those
#   links with relative ones. Moreover, we cannot use `--public-url "./"`
#   CLI argument, because it works… differently (results with `/./` paths).
#   Related GitHub issue: https://github.com/thedodd/trunk/issues/395
public_url = "./"

[serve]
port = 9091
open = true

[clean]
dist = "dist/itch_io"
