name: "shared steps"
description: "Shared steps used to setup prerequisites for other jobs."

# dtolnay/rust-toolchain@stable: https://github.com/marketplace/actions/rustup-toolchain-install
# Swatinem/rust-cache@v2:        https://github.com/marketplace/actions/rust-cache

runs:
  using: "composite"
  steps:
    # order of commands: `Swatinem/rust-cache@v2` relies on `rustc` version activated by `dtolnay/rust-toolchain@stable`
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "20230404-01"
        key: "-${{ matrix.command_variant.cache_sub_key }}-"
